sudo pacman -Sy mingw-w64-gcc \
giflib \
lib32-giflib \
lib32-gnutls \
libxinerama \
lib32-libxinerama \
libxcomposite \
lib32-libxcomposite \
libxxf86vm \
lib32-libxxf86vm \
v4l-utils \
lib32-v4l-utils \
alsa-lib \
lib32-alsa-lib \
libxcomposite \
lib32-libxcomposite \
mesa \
lib32-mesa \
mesa-libgl \
lib32-mesa-libgl \
opencl-icd-loader \
lib32-opencl-icd-loader \
libpulse \
lib32-libpulse \
libva \
lib32-libva \
gtk3 \
lib32-gtk3 \
gst-plugins-base-libs \
lib32-gst-plugins-base-libs \
vulkan-icd-loader \
lib32-vulkan-icd-loader \
sdl2 \
lib32-sdl2 \
libcups \
lib32-libcups \
sane \
libgphoto2 \
ffmpeg \
samba \
opencl-headers
