sudo pacman -Sy alsa-lib \
dbus \
desktop-file-utils \
ffmpeg \
fontconfig \
freetype2 \
giflib \
gnutls \
gst-plugins-base-libs \
gstreamer \
gtk3 \
krb5 \
lib32-alsa-lib \
lib32-fontconfig \
lib32-freetype2 \
lib32-gcc-libs \
lib32-gettext \
lib32-giflib \
lib32-gnutls \
lib32-gst-plugins-base-libs \
lib32-gtk3 \
lib32-libcups \
lib32-libpcap \
lib32-libpulse \
lib32-libva \
lib32-libxcomposite \
lib32-libxcursor \
lib32-libxi \
lib32-libxinerama \
lib32-libxrandr \
lib32-libxxf86vm \
lib32-mesa \
lib32-mesa-libgl \
lib32-opencl-icd-loader \
lib32-sdl2 \
lib32-v4l-utils \
lib32-vulkan-icd-loader \
libcups \
libgphoto2 \
libpcap \
libpulse \
libunwind \
libusb \
libva \
libx11 \
libxcomposite \
libxcursor \
libxext \
libxfixes \
libxi \
libxinerama \
libxrandr \
libxrender \
mesa \
mingw-w64-gcc \
nano \
ocl-icd \
opencl-headers \
opencl-icd-loader \
samba \
sane \
sdl2 \
smbclient \
systemd \
v4l-utils \
vulkan-headers \
vulkan-icd-loader
